---
- name: Create LVMs
  hosts: node1.example.com
  become: yes

  vars_files:
    - lvmvar.yml

  tasks:
  - name: Create physical volume
    shell: "pvcreate {{ item.pv_device }}"
    loop: "{{ lvms }}"
    ignore_errors: yes
    register: pvcreate_output

  - name: debug
    debug:
      var: pvcreate output

  - name: Create volume group
    lvg:
      vg: "{{ item.vg_name }}"
      state: present
    loop: "{{ lvms }}"

  - name: Add physical volume to volume group
    shell: "vgextend {{ item.vg_name }} {{ item.pv_device }}"
    loop: "{{ lvms }}"

  - name: Create logical volume
    lvol:
      vg: "{{ item.vg_name }}"
      lv: "{{ item.name }}"
      size: "{{ item.size }}"
      state: present
    loop: "{{ lvms }}"

  - name: Format logical volume
    filesystem:
      dev: "/dev/mapper/{{ item.vg_name }}-{{ item.name }}"
      fstype: "{{ item.fstype }}"
    loop: "{{ lvms }}"

  - name: Create mount point
    file:
      path: "{{ item.mountpoint }}"
      state: directory
    loop: "{{ lvms }}"

  - name: Mount logical volume
    mount:
      path: "{{ item.mountpoint }}"
      src: "/dev/mapper/{{ item.vg_name }}-{{ item.name }}"
      fstype: "{{ item.fstype }}"
      state: mounted
    loop: "{{ lvms }}"

  - name: Append fstab entry
    lineinfile:
      dest: /etc/fstab
      line: "/dev/mapper/{{ item.vg_name }}-{{ item.name }} {{ item.mountpoint }} {{ item.fstype }} defaults 0 0"
      state: present
    loop: "{{ lvms }}"
