- name: User creating password
  hosts: servers
  vars_files:
    - varfile
  tasks:
    - name: creating users
      user:
        name: "{{ item.username }}"
        comment: "{{ item.comment }}"
        shell: "{{ item.shell }}"
        state: present
        password: "{{ item.password | password_hash('sha512') }}"
      loop: "{{ users }}"
